INSERT INTO Clients (FirstName, LastName, Age) VALUES ('Jan', 'Kowalski', 32)
INSERT INTO Clients (FirstName, LastName, Age) VALUES ('Anna', 'Nowak', 27)
INSERT INTO Clients (FirstName, LastName, Age) VALUES ('Piotr', 'Kowalczyk', 41)
INSERT INTO Clients (FirstName, LastName, Age) VALUES ('Katarzyna', 'Wójcik', 23)
INSERT INTO Clients (FirstName, LastName, Age) VALUES ('Andrzej', 'Kaczmarek', 56)
INSERT INTO Clients (FirstName, LastName, Age) VALUES ('Magdalena', 'Lewandowska', 30)
INSERT INTO Clients (FirstName, LastName, Age) VALUES ('Tomasz', 'Szymański', 38)
INSERT INTO Clients (FirstName, LastName, Age) VALUES ('Alicja', 'Dąbrowska', 29)